import 'map_models.dart';

final List<SurfSpot> globalSurfSpots = [
  // North America - USA
  SurfSpot(id: 's_001', name: 'Pipeline', country: 'USA', region: 'Hawaii', lat: 21.6649, lng: -158.0526, difficulty: 'Advanced', notes: 'World-famous hollow reef break.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_002', name: 'Waikiki', country: 'USA', region: 'Hawaii', lat: 21.2764, lng: -157.8285, difficulty: 'Beginner', notes: 'Gentle longboard waves.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_003', name: 'Malibu', country: 'USA', region: 'California', lat: 34.0379, lng: -118.6779, difficulty: 'Beginner to Intermediate', notes: 'Iconic point break.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_004', name: 'Trestles', country: 'USA', region: 'California', lat: 33.3772, lng: -117.5901, difficulty: 'Intermediate', notes: 'High-performance A-frame.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_005', name: 'Huntington Beach', country: 'USA', region: 'California', lat: 33.6603, lng: -118.0034, difficulty: 'Intermediate', notes: 'Surf City USA pier break.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_006', name: 'Mavericks', country: 'USA', region: 'California', lat: 37.4913, lng: -122.5002, difficulty: 'Advanced', notes: 'Legendary big wave spot.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_007', name: 'Steamer Lane', country: 'USA', region: 'California', lat: 36.9515, lng: -122.0255, difficulty: 'Intermediate', notes: 'Cold water point break.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_008', name: 'Rincon', country: 'USA', region: 'California', lat: 34.3725, lng: -119.4764, difficulty: 'Intermediate', notes: 'The Queen of the Coast.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_009', name: 'Outer Banks', country: 'USA', region: 'North Carolina', lat: 35.5352, lng: -75.4665, difficulty: 'Intermediate', notes: 'Powerful sandbars.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_010', name: 'Cocoa Beach', country: 'USA', region: 'Florida', lat: 28.3200, lng: -80.6076, difficulty: 'Beginner', notes: 'Small, consistent waves.', createdAt: DateTime(2024)),

  // Oceania - Australia
  SurfSpot(id: 's_011', name: 'Snapper Rocks', country: 'Australia', region: 'Queensland', lat: -28.1633, lng: 153.5501, difficulty: 'Advanced', notes: 'The Superbank.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_012', name: 'Bells Beach', country: 'Australia', region: 'Victoria', lat: -38.3705, lng: 144.2831, difficulty: 'Advanced', notes: 'Powerful amphitheater.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_013', name: 'Margaret River', country: 'Australia', region: 'Western Australia', lat: -33.9782, lng: 114.9961, difficulty: 'Advanced', notes: 'Big wave chargers.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_014', name: 'Noosa Heads', country: 'Australia', region: 'Queensland', lat: -26.3813, lng: 153.1022, difficulty: 'Beginner', notes: 'Long, peeling right-hand points.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_015', name: 'Byron Bay', country: 'Australia', region: 'New South Wales', lat: -28.6474, lng: 153.6020, difficulty: 'Beginner', notes: 'The Pass is iconic.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_016', name: 'Kirra', country: 'Australia', region: 'Queensland', lat: -28.1664, lng: 153.5332, difficulty: 'Advanced', notes: 'Fast, hollow tubes.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_017', name: 'Winki Pop', country: 'Australia', region: 'Victoria', lat: -38.3697, lng: 144.2798, difficulty: 'Advanced', notes: 'Fast right-hander.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_018', name: 'Burleigh Heads', country: 'Australia', region: 'Queensland', lat: -28.0874, lng: 153.4542, difficulty: 'Intermediate', notes: 'Classic point break.', createdAt: DateTime(2024)),

  // Asia
  SurfSpot(id: 's_019', name: 'Uluwatu', country: 'Indonesia', region: 'Bali', lat: -8.8315, lng: 115.0853, difficulty: 'Advanced', notes: 'Five distinct peaks.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_020', name: 'Cloud 9', country: 'Philippines', region: 'Siargao', lat: 9.8130, lng: 126.1630, difficulty: 'Advanced', notes: 'Perfect hollow right.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_021', name: 'Padang Padang', country: 'Indonesia', region: 'Bali', lat: -8.8111, lng: 115.1039, difficulty: 'Advanced', notes: 'The Balinese Pipeline.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_022', name: 'Desert Point', country: 'Indonesia', region: 'Lombok', lat: -8.7333, lng: 115.8333, difficulty: 'Advanced', notes: 'Worlds longest tube?', createdAt: DateTime(2024)),
  SurfSpot(id: 's_023', name: 'Canggu', country: 'Indonesia', region: 'Bali', lat: -8.6478, lng: 115.1385, difficulty: 'Intermediate', notes: 'Consistent sand bar.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_024', name: 'Arugam Bay', country: 'Sri Lanka', region: 'East Province', lat: 6.8400, lng: 81.8200, difficulty: 'Intermediate', notes: 'Long right-hand points.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_025', name: 'Hikkaduwa', country: 'Sri Lanka', region: 'South Province', lat: 6.1360, lng: 80.1030, difficulty: 'Beginner to Intermediate', notes: 'Clean A-frame peaks.', createdAt: DateTime(2024)),

  // Europe
  SurfSpot(id: 's_026', name: 'Hossegor', country: 'France', region: 'Landes', lat: 43.6592, lng: -1.4326, difficulty: 'Advanced', notes: 'Powerful beach breaks.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_027', name: 'Mundaka', country: 'Spain', region: 'Basque Country', lat: 43.4076, lng: -2.6974, difficulty: 'Advanced', notes: 'World class river mouth left.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_028', name: 'Peniche', country: 'Portugal', region: 'Leiria', lat: 39.3556, lng: -9.3811, difficulty: 'Intermediate', notes: 'Consistency at Supertubos.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_029', name: 'Nazaré', country: 'Portugal', region: 'Leiria', lat: 39.6012, lng: -9.0701, difficulty: 'Advanced', notes: 'Massive canyon waves.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_030', name: 'Ericeira', country: 'Portugal', region: 'Lisbon', lat: 38.9669, lng: -9.4176, difficulty: 'Intermediate', notes: 'World Surfing Reserve.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_031', name: 'Thurso East', country: 'UK', region: 'Scotland', lat: 58.5956, lng: -3.5111, difficulty: 'Advanced', notes: 'Cold water slab.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_032', name: 'Bundoran', country: 'Ireland', region: 'Donegal', lat: 54.4772, lng: -8.2747, difficulty: 'Intermediate', notes: 'Surfing capital of Ireland.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_033', name: 'Fistral Beach', country: 'UK', region: 'Cornwall', lat: 50.4168, lng: -5.0935, difficulty: 'Beginner to Intermediate', notes: 'UKs premier surf beach.', createdAt: DateTime(2024)),

  // Africa
  SurfSpot(id: 's_034', name: 'Jeffrey\'s Bay', country: 'South Africa', region: 'Eastern Cape', lat: -34.0322, lng: 24.9213, difficulty: 'Advanced', notes: 'The perfect right point.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_035', name: 'Skeleton Bay', country: 'Namibia', region: 'Namib Desert', lat: -23.0000, lng: 14.4000, difficulty: 'Advanced', notes: 'Endless left-hand tube.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_036', name: 'Dungeons', country: 'South Africa', region: 'Cape Town', lat: -34.0500, lng: 18.3300, difficulty: 'Advanced', notes: 'Big wave amphitheater.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_037', name: 'Taghazout', country: 'Morocco', region: 'Souss-Massa', lat: 30.5433, lng: -9.7083, difficulty: 'Intermediate', notes: 'World-famous point breaks.', createdAt: DateTime(2024)),

  // South America
  SurfSpot(id: 's_038', name: 'Chicama', country: 'Peru', region: 'La Libertad', lat: -7.6917, lng: -79.4356, difficulty: 'Intermediate', notes: 'Worlds longest left.', createdAt: DateTime(2023)),
  SurfSpot(id: 's_039', name: 'Pichilemu', country: 'Chile', region: "O'Higgins", lat: -34.3858, lng: -72.0069, difficulty: 'Intermediate', notes: 'Cold water point breaks.', createdAt: DateTime(2023)),
  SurfSpot(id: 's_040', name: 'Itamambuca', country: 'Brazil', region: 'São Paulo', lat: -23.3980, lng: -45.0060, difficulty: 'Intermediate', notes: 'Competitive surf hub.', createdAt: DateTime(2023)),
  SurfSpot(id: 's_041', name: 'Montañita', country: 'Ecuador', region: 'Santa Elena', lat: -2.1287, lng: -80.7516, difficulty: 'Beginner to Intermediate', notes: 'Lively surf village.', createdAt: DateTime(2023)),
  SurfSpot(id: 's_042', name: 'Máncora', country: 'Peru', region: 'Piura', lat: -4.1064, lng: -81.0475, difficulty: 'Beginner', notes: 'Warm water and long lefts.', createdAt: DateTime(2023)),

  // Central America & Caribbean
  SurfSpot(id: 's_043', name: 'Puntarenas', country: 'Costa Rica', region: 'Puntarenas', lat: 9.9763, lng: -84.8289, difficulty: 'Intermediate', notes: 'Consistent Pura Vida peaks.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_044', name: 'La Libertad', country: 'El Salvador', region: 'La Libertad', lat: 13.4880, lng: -89.3220, difficulty: 'Intermediate', notes: 'Right point-break heaven.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_045', name: 'Bocas del Toro', country: 'Panama', region: 'Bocas del Toro', lat: 9.3333, lng: -82.2500, difficulty: 'Intermediate', notes: 'Caribbean reef peaks.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_046', name: 'Rincon', country: 'Puerto Rico', region: 'Western PR', lat: 18.3403, lng: -67.2500, difficulty: 'Intermediate', notes: 'The North Shore of the CARIB.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_047', name: 'Popoyo', country: 'Nicaragua', region: 'Rivas', lat: 11.4500, lng: -86.1167, difficulty: 'Intermediate', notes: 'Offshore winds 300 days/year.', createdAt: DateTime(2024)),

  // Adding more to reach closer to 100...
  SurfSpot(id: 's_048', name: 'Teahupo\'o', country: 'Tahiti', region: 'French Polynesia', lat: -17.8480, lng: -149.2660, difficulty: 'Advanced', notes: 'The heaviest wave.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_049', name: 'Shipstern Bluff', country: 'Australia', region: 'Tasmania', lat: -43.2100, lng: 147.8500, difficulty: 'Advanced', notes: 'The devil\'s horn.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_050', name: 'Lunada Bay', country: 'USA', region: 'California', lat: 33.7900, lng: -118.4100, difficulty: 'Advanced', notes: 'Localized point break.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_051', name: 'Saltburn', country: 'UK', region: 'East Cleveland', lat: 54.5800, lng: -0.9700, difficulty: 'Beginner', notes: 'Consistent north east peaks.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_052', name: 'Croyde Bay', country: 'UK', region: 'North Devon', lat: 51.1300, lng: -4.2300, difficulty: 'Intermediate', notes: 'Heavy beach break.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_053', name: 'Sennen Cove', country: 'UK', region: 'West Cornwall', lat: 50.0700, lng: -5.7000, difficulty: 'Beginner', notes: 'Reliable beach break.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_054', name: 'Gower Peninsula', country: 'UK', region: 'South Wales', lat: 51.6000, lng: -4.2000, difficulty: 'Intermediate', notes: 'Diverse range of breaks.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_055', name: 'Lacanau', country: 'France', region: 'Gironde', lat: 44.9800, lng: -1.2000, difficulty: 'Intermediate', notes: 'Lively surf town.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_056', name: 'Biarritz', country: 'France', region: 'Pyrenees-Atlantiques', lat: 43.4800, lng: -1.5600, difficulty: 'Beginner', notes: 'The birth of Euro surf.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_057', name: 'Tarifa', country: 'Spain', region: 'Andalusia', lat: 36.0100, lng: -5.6000, difficulty: 'Intermediate', notes: 'Wind and kitesurfing hub too.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_058', name: 'Zarautz', country: 'Spain', region: 'Basque Country', lat: 43.2800, lng: -2.1700, difficulty: 'Beginner', notes: 'Long sandy beach peak.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_059', name: 'Somo', country: 'Spain', region: 'Cantabria', lat: 43.4500, lng: -3.7500, difficulty: 'Beginner', notes: 'Wide consistent beach.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_060', name: 'Praia do Guincho', country: 'Portugal', region: 'Cascais', lat: 38.7300, lng: -9.4700, difficulty: 'Intermediate', notes: 'Windy but fast.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_061', name: 'Supernatural (Supertubos)', country: 'Portugal', region: 'Peniche', lat: 39.3400, lng: -9.3600, difficulty: 'Advanced', notes: 'Hollow, fast pits.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_062', name: 'Agadir', country: 'Morocco', region: 'Souss-Massa', lat: 30.4200, lng: -9.6000, difficulty: 'Beginner', notes: 'Gateway to point breaks.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_063', name: 'Anchor Point', country: 'Morocco', region: 'Taghazout', lat: 30.5500, lng: -9.7200, difficulty: 'Advanced', notes: 'Long, legendary right.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_064', name: 'Killer Point', country: 'Morocco', region: 'Taghazout', lat: 30.5600, lng: -9.7400, difficulty: 'Intermediate', notes: 'Powerful right points.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_065', name: 'Immsouane', country: 'Morocco', region: 'Coast', lat: 30.8400, lng: -9.8200, difficulty: 'Beginner', notes: 'Endless longboard wave.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_066', name: 'Dakhla', country: 'Morocco', region: 'Western Sahara', lat: 23.7200, lng: -15.9500, difficulty: 'Intermediate', notes: 'Vast lagoon and waves.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_067', name: 'Victoria Bay', country: 'South Africa', region: 'George', lat: -34.0000, lng: 22.5500, difficulty: 'Intermediate', notes: 'Gems of the Garden Route.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_068', name: 'Elands Bay', country: 'South Africa', region: 'West Coast', lat: -32.3100, lng: 18.3300, difficulty: 'Intermediate', notes: 'Perfect left points.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_069', name: 'Coffee Bay', country: 'South Africa', region: 'Wild Coast', lat: -31.9800, lng: 29.1500, difficulty: 'Intermediate', notes: 'Untouched rugged beauty.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_070', name: 'Long Beach', country: 'South Africa', region: 'Kommetjie', lat: -34.1300, lng: 18.3200, difficulty: 'Intermediate', notes: 'Consistent A-frames.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_071', name: 'Muizenberg', country: 'South Africa', region: 'Cape Town', lat: -34.1100, lng: 18.4700, difficulty: 'Beginner', notes: 'Best learner beach in CT.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_072', name: 'Midigama', country: 'Sri Lanka', region: 'South Coast', lat: 5.9700, lng: 80.3900, difficulty: 'Intermediate', notes: 'Rams Right is heavy.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_073', name: 'Weligama', country: 'Sri Lanka', region: 'South Coast', lat: 5.9700, lng: 80.4300, difficulty: 'Beginner', notes: 'Sandy bottom peaks.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_074', name: 'The Ments (Mentawais)', country: 'Indonesia', region: 'Sumatra', lat: -2.1500, lng: 99.6300, difficulty: 'Advanced', notes: 'World\'s best playground.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_075', name: 'G-Land', country: 'Indonesia', region: 'Java', lat: -8.7300, lng: 114.3500, difficulty: 'Advanced', notes: 'Graveyard of surfers.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_076', name: 'Kuta Beach', country: 'Indonesia', region: 'Bali', lat: -8.7200, lng: 115.1700, difficulty: 'Beginner', notes: 'Crowded but fun beachies.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_077', name: 'Keramas', country: 'Indonesia', region: 'Bali', lat: -8.5900, lng: 115.3500, difficulty: 'Advanced', notes: 'High performance right.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_078', name: 'Medewi', country: 'Indonesia', region: 'Bali', lat: -8.4100, lng: 114.8100, difficulty: 'Beginner', notes: 'Longest left in Bali.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_079', name: 'Tavarua', country: 'Fiji', region: 'Viti Levu', lat: -17.8500, lng: 177.2000, difficulty: 'Advanced', notes: 'Cloudbreak is world-class.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_080', name: 'Namotu', country: 'Fiji', region: 'Viti Levu', lat: -17.8600, lng: 177.2100, difficulty: 'Intermediate', notes: 'Namotu Left is fun.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_081', name: 'Aitutaki', country: 'Cook Islands', region: 'Aitutaki', lat: -18.8500, lng: -159.7800, difficulty: 'Intermediate', notes: 'Crystal clear reef peaks.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_082', name: 'Raglan', country: 'New Zealand', region: 'Waikato', lat: -37.8200, lng: 174.8300, difficulty: 'Intermediate', notes: 'Indless left points.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_083', name: 'Piha Beach', country: 'New Zealand', region: 'Auckland', lat: -36.9500, lng: 174.4700, difficulty: 'Intermediate', notes: 'Rugged black sand beach.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_084', name: 'Dunedin', country: 'New Zealand', region: 'Otago', lat: -45.8700, lng: 170.5000, difficulty: 'Intermediate', notes: 'Cold and consistent south.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_085', name: 'Arica', country: 'Chile', region: 'Arica', lat: -18.4800, lng: -70.3200, difficulty: 'Advanced', notes: 'Powerful reef breaks.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_086', name: 'Punta de Lobos', country: 'Chile', region: 'Pichilemu', lat: -34.4200, lng: -72.0500, difficulty: 'Advanced', notes: 'Iconic big wave point.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_087', name: 'Playa Cavancha', country: 'Chile', region: 'Iquique', lat: -20.2100, lng: -70.1500, difficulty: 'Intermediate', notes: 'Desert surf city.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_088', name: 'Mar del Plata', country: 'Argentina', region: 'Buenos Aires', lat: -38.0000, lng: -57.5500, difficulty: 'Beginner', notes: 'Heart of Argentine surf.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_089', name: 'Playa Venao', country: 'Panama', region: 'Azuero', lat: 7.4300, lng: -80.1900, difficulty: 'Beginner', notes: 'Friendly beach peaks.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_090', name: 'Santa Teresa', country: 'Costa Rica', region: 'Nicoya', lat: 9.6400, lng: -85.1700, difficulty: 'Intermediate', notes: 'Consistent beach breaks.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_091', name: 'Pavones', country: 'Costa Rica', region: 'South', lat: 8.3900, lng: -83.1300, difficulty: 'Intermediate', notes: 'One of the longest lefts.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_092', name: 'Tamarindo', country: 'Costa Rica', region: 'Guanacaste', lat: 10.3000, lng: -85.8400, difficulty: 'Beginner', notes: 'Bustling surf town.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_093', name: 'El Tunco', country: 'El Salvador', region: 'La Libertad', lat: 13.4900, lng: -89.3800, difficulty: 'Intermediate', notes: 'Party and right points.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_094', name: 'Sayulita', country: 'Mexico', region: 'Nayarit', lat: 20.8700, lng: -105.4400, difficulty: 'Beginner', notes: 'Hipster longboard haven.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_095', name: 'Puerto Escondido', country: 'Mexico', region: 'Oaxaca', lat: 15.8600, lng: -97.0800, difficulty: 'Advanced', notes: 'The Mexican Pipeline.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_096', name: 'Scorpion Bay', country: 'Mexico', region: 'Baja', lat: 26.2400, lng: -112.4700, difficulty: 'Intermediate', notes: 'Multiple point peaks.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_097', name: 'Tofino', country: 'Canada', region: 'BC', lat: 49.1200, lng: -125.9000, difficulty: 'Beginner to Intermediate', notes: 'Canada\'s surf capital.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_098', name: 'Lawrencetown', country: 'Canada', region: 'Nova Scotia', lat: 44.6400, lng: -63.3400, difficulty: 'Intermediate', notes: 'Cold water east coast.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_099', name: 'Long Beach', country: 'USA', region: 'New York', lat: 40.5800, lng: -73.6600, difficulty: 'Intermediate', notes: 'Best of NY surf.', createdAt: DateTime(2024)),
  SurfSpot(id: 's_100', name: 'Manasquan Inlet', country: 'USA', region: 'New Jersey', lat: 40.1000, lng: -74.0300, difficulty: 'Intermediate', notes: 'Classic Jersey peak.', createdAt: DateTime(2024)),
];
