// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx9a3Lonok3QQAftRt0tFH5GOeIv5pKS0',
    appId: '1:607370528361:web:065dba42ff1235f1a0c4f8',
    messagingSenderId: '607370528361',
    projectId: 'smart-surf-62031',
    authDomain: 'smart-surf-62031.firebaseapp.com',
    storageBucket: 'smart-surf-62031.firebasestorage.app',
    measurementId: 'G-W3YXH47VM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADz6CLY2XwVgINgCQwU75IKhmm6W09YrQ',
    appId: '1:607370528361:android:ea205f782743f201a0c4f8',
    messagingSenderId: '607370528361',
    projectId: 'smart-surf-62031',
    storageBucket: 'smart-surf-62031.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHQ-uFUDSLiWUxaP6FyKrkXe1JqenL_Qo',
    appId: '1:607370528361:ios:a0fe474b98d24222a0c4f8',
    messagingSenderId: '607370528361',
    projectId: 'smart-surf-62031',
    storageBucket: 'smart-surf-62031.firebasestorage.app',
    iosClientId: '607370528361-vnuhjtog8125a78ov0jks2k5s1m7ud1n.apps.googleusercontent.com',
    iosBundleId: 'com.christinestclair.smartsurf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHQ-uFUDSLiWUxaP6FyKrkXe1JqenL_Qo',
    appId: '1:607370528361:ios:10308094c0dc6fffa0c4f8',
    messagingSenderId: '607370528361',
    projectId: 'smart-surf-62031',
    storageBucket: 'smart-surf-62031.firebasestorage.app',
    iosClientId: '607370528361-82hb65cj6sg698bfudin26o47t27b7ot.apps.googleusercontent.com',
    iosBundleId: 'com.example.surfPassport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx9a3Lonok3QQAftRt0tFH5GOeIv5pKS0',
    appId: '1:607370528361:web:b7ebe4b13355ccf4a0c4f8',
    messagingSenderId: '607370528361',
    projectId: 'smart-surf-62031',
    authDomain: 'smart-surf-62031.firebaseapp.com',
    storageBucket: 'smart-surf-62031.firebasestorage.app',
    measurementId: 'G-KQ54YM0EBN',
  );

}